apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ha8r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ha8r
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ha8r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ha8r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ha8r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dodv-tenant/rhtap-demo-app/hacbs-test-project-ha8r@sha256:e67d9afb0af98245c7e55135653a05867f0e9c1661aa9f5a510dcc1b6ea626f4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
