apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ha8r
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dodv-tenant/rhtap-demo-app/hacbs-test-project-ha8r@sha256:e67d9afb0af98245c7e55135653a05867f0e9c1661aa9f5a510dcc1b6ea626f4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
