apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ha8r
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dodv-tenant/rhtap-demo-app/hacbs-test-project-ha8r@sha256:a02757cb18c4edb796a9a214a58a8c8a700651ebe120d4a1cba78635a04758fb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
